# Generated by Django 4.2.4 on 2023-08-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "ID",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("UserAccountID", models.IntegerField()),
                ("Content", models.TextField()),
                ("Status", models.IntegerField()),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("LastModifiedDate", models.DateTimeField()),
            ],
            options={"db_table": "Comment",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("UserAccountID", models.IntegerField()),
                ("Title", models.CharField(max_length=512)),
                ("Content", models.TextField()),
                ("totalAnswer", models.IntegerField()),
                ("Like", models.IntegerField()),
                ("View", models.IntegerField()),
                ("Status", models.IntegerField()),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("LastModifiedDate", models.DateTimeField()),
                ("LastModifiedBy", models.IntegerField()),
            ],
            options={"db_table": "Post",},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=512)),
            ],
            options={"db_table": "Tag",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "ID",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("DisplayName", models.CharField(max_length=512)),
                ("Email", models.CharField(max_length=512)),
                ("Password", models.CharField(max_length=512)),
                ("AboutMe", models.TextField()),
                ("Location", models.CharField(max_length=512)),
                ("RoleID", models.IntegerField()),
                ("RoleName", models.CharField(max_length=512)),
                ("Status", models.IntegerField()),
                ("Level", models.CharField(max_length=512)),
                ("CreatedDate", models.DateTimeField()),
            ],
            options={"db_table": "UserAccount",},
        ),
        migrations.CreateModel(
            name="Posts_Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user_app.post"
                    ),
                ),
                (
                    "Tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user_app.tag"
                    ),
                ),
            ],
            options={"db_table": "Posts_Tags",},
        ),
        migrations.CreateModel(
            name="Posts_Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.comment",
                    ),
                ),
                (
                    "Post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user_app.post"
                    ),
                ),
            ],
            options={"db_table": "Posts_Comments",},
        ),
        migrations.AddField(
            model_name="post",
            name="CommentID",
            field=models.ManyToManyField(
                related_name="Posts_Comment",
                through="user_app.Posts_Comments",
                to="user_app.comment",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="TagID",
            field=models.ManyToManyField(
                related_name="Posts_Title",
                through="user_app.Posts_Tags",
                to="user_app.tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="posts_tags",
            constraint=models.UniqueConstraint(
                fields=("Post", "Tag"), name="unique_Post_Tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="posts_comments",
            constraint=models.UniqueConstraint(
                fields=("Post", "Comment"), name="unique_Post_Comment"
            ),
        ),
    ]
